name: FixDiscover for finding backport candidates in systemd JIRA issues
on:
  schedule:
    # Workflow runs every week on sunday at 23:00 UTC
    - cron: '0 23 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fixdiscover:
    if: github.repository == 'redhat-plumbers/.github'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - run: npx fixdiscover --component systemd
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
